/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/social/discord.glb -o src/Components/3D/Discord.jsx -k -r public 
Author: pengedarseni (https://sketchfab.com/pengedarseni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-discord-logo-7675c2f3bfb54bf4b68d3df338457ae5
Title: 3D Discord Logo
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Discord(props) {
  const { nodes, materials } = useGLTF("/models/social/discord.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <group name="Curve018_0" position={[0, 3, 6]} scale={13.782}>
          <mesh
            name="Object_4"
            geometry={nodes.Object_4.geometry}
            material={materials["glossy_putih.001"]}
          />
          <mesh
            name="Object_5"
            geometry={nodes.Object_5.geometry}
            material={materials.glossy_discord}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/social/discord.glb");
