/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/social/github.glb -o src/Components/3D/Github.jsx -k -r public 
Author: pengedarseni (https://sketchfab.com/pengedarseni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-github-logo-441d03d1076b44f483df551e02d970fe
Title: 3D Github Logo
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Github(props) {
  const { nodes, materials } = useGLTF("/models/social/github.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="Curve012_0"
        position={[-0.055, 2.945, 6.336]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={28.364}
      >
        <mesh
          name="Object_4"
          geometry={nodes.Object_4.geometry}
          material={materials.glossy_putih}
        />
        <mesh
          name="Object_5"
          geometry={nodes.Object_5.geometry}
          material={materials.github}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/social/github.glb");
