/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/house2.glb -o src/Components/3D/House2.jsx -k -r public 
*/

import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";

import { useControls } from "leva";

export function House2(props) {
  const { nodes, materials } = useGLTF("/models/house2.glb");
  const planeDetails = useControls("Plane Details", {
    position: {
      value: [-0.519, 1.119, -1.036],
      step: 0.01,
    },
    rotation: {
      value: [0, -0.5, 0],
      step: 0.01,
    },
    height: {
      value: 0.2,
      step: 0.01,
    },
    width: {
      value: 0.2,
      step: 0.01,
    },
  });
  const texture = useTexture("Textures/laptop-Texture.png");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Wall"
        geometry={nodes.Wall.geometry}
        material={materials["3"]}
      />

      <group position={[0, -0.3, 0]} className="objects-ontable">
        <group className="monitor-1">
          <group
            name="Monitor_-_1"
            position={[-0.519, 1.53, -0.989]}
            scale={1.199}
          >
            <mesh
              name="Plane088"
              geometry={nodes.Plane088.geometry}
              material={materials["9"]}
            />
            <mesh
              name="Plane088_1"
              geometry={nodes.Plane088_1.geometry}
              material={materials["7"]}
            >
              <meshBasicMaterial map={texture} />
            </mesh>
          </group>

          <mesh
            name="Monitor_Stand_-_1"
            geometry={nodes["Monitor_Stand_-_1"].geometry}
            material={materials["9"]}
            position={[-0.519, 1.119, -1.036]}
            scale={[0.155, 0.155, 0.092]}
          />
        </group>

        <group className="monitor-2">
          <group
            name="Monitor_-_2"
            position={[0.257, 1.58, -0.882]}
            rotation={[0, -0.355, -Math.PI / 2]}
            scale={[0.988, 1.199, 1.199]}
          >
            <mesh
              name="Plane051"
              geometry={nodes.Plane051.geometry}
              material={materials["9"]}
            />
            <mesh
              name="Plane051_1"
              geometry={nodes.Plane051_1.geometry}
              material={materials["7"]}
            />
          </group>

          <mesh
            name="Monitor_Stand_-_2"
            geometry={nodes["Monitor_Stand_-_2"].geometry}
            material={materials["9"]}
            position={[0.274, 1.119, -0.926]}
            rotation={[0, -0.355, 0]}
            scale={[0.155, 0.155, 0.092]}
          />
        </group>

        <group
          name="Mouse"
          position={[-0.083, 1.162, -0.714]}
          rotation={[0, 0.185, 0]}
          scale={0.028}
        >
          <mesh
            name="Cylinder018"
            geometry={nodes.Cylinder018.geometry}
            material={materials["9"]}
          />
          <mesh
            name="Cylinder018_1"
            geometry={nodes.Cylinder018_1.geometry}
            material={materials["4"]}
          />
        </group>

        <group
          name="Keyboard001"
          position={[-0.469, 1.132, -0.645]}
          scale={0.039}
        >
          <mesh
            name="Plane001"
            geometry={nodes.Plane001.geometry}
            material={materials["9"]}
          />
          <mesh
            name="Plane001_1"
            geometry={nodes.Plane001_1.geometry}
            material={materials["6"]}
          />
        </group>
      </group>

      <mesh className="vs-code-screen" position={[-0.52, 1.23, -0.99]}>
        <planeGeometry args={[0.85, 0.58]} />
        <meshBasicMaterial map={texture} />
      </mesh>

      <mesh
        name="Chair"
        geometry={nodes.Chair.geometry}
        material={materials["4"]}
        position={[-0.04, 0.107, -0.44]}
        rotation={[0.138, 0, 0.136]}
        scale={[0.53, 0.437, 0.53]}
      />

      <group name="Table" position={[-1.077, 0.254, -0.801]} scale={1.199}>
        <mesh
          name="Cube020"
          geometry={nodes.Cube020.geometry}
          material={materials["5"]}
        />
        <mesh
          name="Cube020_1"
          geometry={nodes.Cube020_1.geometry}
          material={materials["2"]}
        />
      </group>

      <group name="Window" position={[0.95, 1.854, -1.238]} scale={1.058}>
        <mesh
          name="Cube012"
          geometry={nodes.Cube012.geometry}
          material={materials["4"]}
        />
        <mesh
          name="Cube012_1"
          geometry={nodes.Cube012_1.geometry}
          material={materials["7"]}
        />
      </group>
      <mesh
        name="Paper_-_1"
        geometry={nodes["Paper_-_1"].geometry}
        material={materials["7"]}
        position={[-1.231, 1.333, 1.045]}
        rotation={[-0.325, 0, 0]}
      />
      <mesh
        name="Framework"
        geometry={nodes.Framework.geometry}
        material={materials["4"]}
        position={[-1.239, 1.683, 0.633]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.487, 0.487, 0.636]}
      />
      <mesh
        name="Pin_-_1"
        geometry={nodes["Pin_-_1"].geometry}
        material={materials["8"]}
        position={[-1.133, 1.474, 0.861]}
        rotation={[-0.325, 0, -Math.PI / 2]}
        scale={0.062}
      />
      <group
        name="Chart_-_1"
        position={[-1.19, 1.909, 0.92]}
        rotation={[1.681, 0, -Math.PI / 2]}
        scale={0.09}
      >
        <mesh
          name="Plane066"
          geometry={nodes.Plane066.geometry}
          material={materials["8"]}
        />
        <mesh
          name="Plane066_1"
          geometry={nodes.Plane066_1.geometry}
          material={materials["5"]}
        />
        <mesh
          name="Plane066_2"
          geometry={nodes.Plane066_2.geometry}
          material={materials["9"]}
        />
      </group>
      <group
        name="Clock"
        position={[-1.202, 2.022, -0.612]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <mesh
          name="Plane067"
          geometry={nodes.Plane067.geometry}
          material={materials["9"]}
        />
        <mesh
          name="Plane067_1"
          geometry={nodes.Plane067_1.geometry}
          material={materials["4"]}
        />
        <mesh
          name="Plane067_2"
          geometry={nodes.Plane067_2.geometry}
          material={materials["6"]}
        />
      </group>
      <mesh
        name="Paper_-_2"
        geometry={nodes["Paper_-_2"].geometry}
        material={materials["9"]}
        position={[-1.231, 1.149, 0.387]}
        rotation={[0.325, 0, -Math.PI]}
        scale={-0.745}
      />
      <mesh
        name="Pin_-_2"
        geometry={nodes["Pin_-_2"].geometry}
        material={materials["5"]}
        position={[-1.133, 1.314, 0.334]}
        rotation={[0.325, 0, Math.PI / 2]}
        scale={-0.062}
      />
      <group
        name="Chart_-_2"
        position={[-1.236, 1.759, 0.258]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.319}
      >
        <mesh
          name="Circle022"
          geometry={nodes.Circle022.geometry}
          material={materials["8"]}
        />
        <mesh
          name="Circle022_1"
          geometry={nodes.Circle022_1.geometry}
          material={materials["5"]}
        />
        <mesh
          name="Circle022_2"
          geometry={nodes.Circle022_2.geometry}
          material={materials["9"]}
        />
      </group>
      <mesh
        name="Floor_-_1_"
        geometry={nodes["Floor_-_1_"].geometry}
        material={materials["1"]}
        position={[-0.013, 1.259, -0.018]}
      />
      <mesh
        name="Floor_-_2"
        geometry={nodes["Floor_-_2"].geometry}
        material={materials["2"]}
        position={[0.245, 0.001, -0.046]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.974}
      />
    </group>
  );
}

useGLTF.preload("/models/house2.glb");
