/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/social/linkdin.glb -o src/Components/3D/Linkdin.jsx -k -r public 
Author: pengedarseni (https://sketchfab.com/pengedarseni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-linkedin-logo-e8786a94c6a942c594696d58d8c59a50
Title: 3D Linkedin Logo
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Linkdin(props) {
  const { nodes, materials } = useGLTF("/models/social/linkdin.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <group name="Cylinder007_0" position={[0, 3, 6]} scale={0.843}>
          <mesh
            name="Object_4"
            geometry={nodes.Object_4.geometry}
            material={materials.glossy_linkedin}
          />
          <mesh
            name="Object_5"
            geometry={nodes.Object_5.geometry}
            material={materials.glossy_putih}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/social/linkdin.glb");
