/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/coconutTree.glb -o src/Components/3D/Tree.jsx -k -r public 
Author: Matrix Rex (https://sketchfab.com/matrixrex)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-coconut-3-17082910370e4f43ba176c9412a380fe
Title: Low poly Coconut 3
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Tree(props) {
  const { nodes, materials } = useGLTF("/models/coconutTree.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.156}
      >
        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
          <group
            name="Coconut_Leaves015_1"
            position={[8.216, 19.019, -6.127]}
            rotation={[2.871, -0.334, -3.042]}
          >
            <mesh
              name="Object_6"
              geometry={nodes.Object_6.geometry}
              material={materials.Coconut_leaf_1}
            />
            <mesh
              name="Object_7"
              geometry={nodes.Object_7.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <group
            name="Coconut_Leaves016_2"
            position={[8.166, 18.787, -6.435]}
            rotation={[-0.323, -0.298, 0.187]}
          >
            <mesh
              name="Object_9"
              geometry={nodes.Object_9.geometry}
              material={materials.Coconut_leaf_1}
            />
            <mesh
              name="Object_10"
              geometry={nodes.Object_10.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <group
            name="Coconut_Leaves017_3"
            position={[8.216, 19.019, -6.127]}
            rotation={[2.024, -1.175, 2.189]}
          >
            <mesh
              name="Object_12"
              geometry={nodes.Object_12.geometry}
              material={materials.Coconut_leaf_3}
            />
            <mesh
              name="Object_13"
              geometry={nodes.Object_13.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <group
            name="Coconut_Leaves018_4"
            position={[8.306, 19.029, -6.194]}
            rotation={[-0.575, 0.98, 0.117]}
          >
            <mesh
              name="Object_15"
              geometry={nodes.Object_15.geometry}
              material={materials.Coconut_leaf_1}
            />
            <mesh
              name="Object_16"
              geometry={nodes.Object_16.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <group
            name="Coconut_Leaves019_5"
            position={[8.627, 19.063, -6.432]}
            rotation={[2.605, -0.855, -2.834]}
          >
            <mesh
              name="Object_18"
              geometry={nodes.Object_18.geometry}
              material={materials.Coconut_leaf_1}
            />
            <mesh
              name="Object_19"
              geometry={nodes.Object_19.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <group
            name="Coconut_Leaves020_6"
            position={[8.306, 19.029, -6.194]}
            rotation={[2.94, 0.246, 2.834]}
          >
            <mesh
              name="Object_21"
              geometry={nodes.Object_21.geometry}
              material={materials.Coconut_leaf_3}
            />
            <mesh
              name="Object_22"
              geometry={nodes.Object_22.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <group
            name="Coconut_Leaves021_7"
            position={[8.657, 18.892, -6.147]}
            rotation={[-3.057, 0.946, 2.189]}
          >
            <mesh
              name="Object_24"
              geometry={nodes.Object_24.geometry}
              material={materials.Coconut_leaf_1}
            />
            <mesh
              name="Object_25"
              geometry={nodes.Object_25.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <group
            name="Coconut_Leaves022_8"
            position={[8.36, 18.715, -6.63]}
            rotation={[0.187, -0.797, -0.065]}
          >
            <mesh
              name="Object_27"
              geometry={nodes.Object_27.geometry}
              material={materials.Coconut_leaf_1}
            />
            <mesh
              name="Object_28"
              geometry={nodes.Object_28.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <group
            name="Coconut_Leaves023_9"
            position={[8.325, 19.263, -6.515]}
            rotation={[-2.118, 1.293, 2.358]}
          >
            <mesh
              name="Object_30"
              geometry={nodes.Object_30.geometry}
              material={materials.Coconut_leaf_3}
            />
            <mesh
              name="Object_31"
              geometry={nodes.Object_31.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <group
            name="Coconut_Leaves024_10"
            position={[8.564, 18.888, -6.057]}
            rotation={[2.906, 0.471, 2.499]}
          >
            <mesh
              name="Object_33"
              geometry={nodes.Object_33.geometry}
              material={materials.Coconut_leaf_1}
            />
            <mesh
              name="Object_34"
              geometry={nodes.Object_34.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <group
            name="Coconut_Leaves025_11"
            position={[8.408, 18.924, -6.675]}
            rotation={[0.02, -1.014, 0.817]}
          >
            <mesh
              name="Object_36"
              geometry={nodes.Object_36.geometry}
              material={materials.Coconut_leaf_1}
            />
            <mesh
              name="Object_37"
              geometry={nodes.Object_37.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <group
            name="Coconut_Leaves026_12"
            position={[8.538, 18.967, -6.08]}
            rotation={[2.677, -0.306, 2.419]}
          >
            <mesh
              name="Object_39"
              geometry={nodes.Object_39.geometry}
              material={materials.Coconut_leaf_3}
            />
            <mesh
              name="Object_40"
              geometry={nodes.Object_40.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <group
            name="Coconut_Leaves027_13"
            position={[8.555, 19.227, -5.778]}
            rotation={[-0.521, 0.349, 0.78]}
          >
            <mesh
              name="Object_42"
              geometry={nodes.Object_42.geometry}
              material={materials.Coconut_leaf_1}
            />
            <mesh
              name="Object_43"
              geometry={nodes.Object_43.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <group
            name="Coconut_Leaves028_14"
            position={[9.103, 19.16, -6.037]}
            rotation={[2.387, -1.058, 1.905]}
          >
            <mesh
              name="Object_45"
              geometry={nodes.Object_45.geometry}
              material={materials.Coconut_leaf_1}
            />
            <mesh
              name="Object_46"
              geometry={nodes.Object_46.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <group
            name="Coconut_Leaves029_15"
            position={[8.671, 18.862, -5.673]}
            rotation={[-0.451, 0.509, -0.554]}
          >
            <mesh
              name="Object_48"
              geometry={nodes.Object_48.geometry}
              material={materials.Coconut_leaf_3}
            />
            <mesh
              name="Object_49"
              geometry={nodes.Object_49.geometry}
              material={materials.Coconut_leaf_2}
            />
          </group>
          <mesh
            name="Object_4"
            geometry={nodes.Object_4.geometry}
            material={materials.Coconut_trunk}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/coconutTree.glb");
