export const config = {
  sections: ["About", "Skills", "Projects", "Contact"],
  title: "Hello I'm",
  subtitle: "Nitesh Kushwaha",
  skills : [
    { name: "HTML", color: "#E44D26", textColor: "#FFFFFF" },
    { name: "CSS", color: "#264DE4", textColor: "#FFFFFF" },
    { name: "JS", color: "#F7DF1E", textColor: "#000000" },
    { name: "React", color: "#61DAFB", textColor: "#000000" },
    { name: "Docker", color: "#2496ED", textColor: "#FFFFFF" },
    { name: "ThreeJS", color: "#000000", textColor: "#FFFFFF" },
    { name: "Express", color: "#4A4A4A", textColor: "#FFFFFF" },
    { name: "NodeJs", color: "#339933", textColor: "#FFFFFF" },
    { name: "MongoDB", color: "#4DB33D", textColor: "#FFFFFF" },
    { name: "Git", color: "#F05032", textColor: "#FFFFFF" },
    { name: "GitHub", color: "#181717", textColor: "#FFFFFF" },
    { name: "Linux", color: "#FCC624", textColor: "#000000" },
    { name: "NextJS", color: "#0070F3", textColor: "#FFFFFF" },
  ],
};
